import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The terms and conditions governing your use of letsthinkpositive.com.',
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: `By accessing or using letsthinkpositive.com ("the Platform"), you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the Platform. We reserve the right to update these terms at any time, with notice provided to registered users via email.`,
  },
  {
    title: '2. Account Registration',
    body: `You must be at least 13 years old to create an account. You are responsible for maintaining the confidentiality of your password and for all activity that occurs under your account. You agree to provide accurate information and to update it as necessary. We reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: '3. Acceptable Use',
    body: `You agree not to: post content that is hateful, discriminatory, threatening, or sexually explicit; harass or bully other members; spam or post unsolicited commercial content; impersonate another person; attempt to gain unauthorised access to any part of the Platform; scrape or mass-download Platform content; or use the Platform for any unlawful purpose.`,
  },
  {
    title: '4. Community Content',
    body: `By posting content to the Community, Circles, or Blog, you grant letsthinkpositive.com a non-exclusive, royalty-free licence to display that content on the Platform. You retain ownership of your content. You are solely responsible for the content you post. We reserve the right to remove content that violates these terms, without prior notice.`,
  },
  {
    title: '5. AI Features (Bit & Calm Coach)',
    body: `The Bit chat companion and Calm Coach are AI-powered features intended for general wellness support only. They are not a substitute for professional medical, psychological, or therapeutic advice. Responses are generated by artificial intelligence and may occasionally be inaccurate. Never use these features in a mental health emergency — please contact a qualified professional or emergency services instead.`,
  },
  {
    title: '6. Wellness Content Disclaimer',
    body: `All wellness content on the Platform — including articles, challenge programmes, meditation guides, and affirmations — is provided for general informational purposes only. It is not intended as, and should not be taken as, medical advice. Always consult a qualified healthcare professional before making changes to your health, diet, or exercise routine.`,
  },
  {
    title: '7. Intellectual Property',
    body: `All original content on the Platform — including the brand, logo, articles, and design — is owned by Tapas Pattanaik / letsthinkpositive.com and may not be reproduced without written permission. User-generated content remains the property of its creator, subject to the licence in Section 4.`,
  },
  {
    title: '8. Privacy',
    body: `Your use of the Platform is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please read it carefully.`,
  },
  {
    title: '9. Limitation of Liability',
    body: `To the maximum extent permitted by law, letsthinkpositive.com and its founders shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform. The Platform is provided "as is" without warranties of any kind, expressed or implied.`,
  },
  {
    title: '10. Governing Law',
    body: `These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of India.`,
  },
  {
    title: '11. Contact',
    body: `For questions about these Terms, contact us at hello@letsthinkpositive.com.`,
  },
]

export default function TermsPage() {
  return (
    <>
      <section className="bg-gradient-to-br from-teal-deep to-teal-dark py-16 px-[5%] text-white text-center">
        <h1 className="font-display text-[clamp(2rem,3.5vw,2.8rem)] font-bold mb-3">Terms &amp; Conditions</h1>
        <p className="text-white/70 text-[1rem]">Last updated: January 2026 · Effective immediately</p>
      </section>

      <article className="max-w-[760px] mx-auto py-16 px-[5%]">
        <p className="text-text-mid text-[1rem] leading-[1.9] mb-10">
          Please read these Terms &amp; Conditions carefully before using <strong className="text-teal-deep">letsthinkpositive.com</strong>.
          They govern your relationship with the Platform and your use of all its features.
        </p>

        <div className="space-y-10">
          {sections.map(s => (
            <section key={s.title}>
              <h2 className="font-display text-[1.15rem] font-semibold text-charcoal mb-3">{s.title}</h2>
              <p className="text-text-mid text-[0.95rem] leading-[1.85]">{s.body}</p>
            </section>
          ))}
        </div>

        <div className="mt-14 pt-8 border-t border-teal-light flex flex-col sm:flex-row gap-4 text-[0.85rem] text-text-xlight">
          <Link href="/privacy"    className="hover:text-teal-deep transition-colors no-underline">Privacy Policy</Link>
          <Link href="/disclaimer" className="hover:text-teal-deep transition-colors no-underline">Disclaimer</Link>
          <Link href="/contact"    className="hover:text-teal-deep transition-colors no-underline">Contact Us</Link>
        </div>
      </article>
    </>
  )
}
